### ISSUE TITLE
Markdown instead of docx

### ISSUE THREAD

**Issue by sk22** [Korlimann/MixnJuice#12]
Please use a plain text/markdown file instead of the ideas docx file. Docx files can not easily be versioned because it's in a binary format. Also, it can't be edited with a text editor.

So it'd probably be best to change the docx file to a text-based file such as Markdown (which can contain formatting and be viewed directly via GitHub)

**Comment by chommsi** [comment]
Already discussed that, no need for further discussion

**Comment by pscn** [comment]
docx content is [here](https://github.com/Korlimann/MixnJuice/wiki/Ideas,-Suggestions-and-Features)
