### ISSUE TITLE
RFC#2.3 Frontend Tech

### ISSUE THREAD

**Issue by mckernanin** [Korlimann/MixnJuice#22]
Splitting off another RFC for frontend discussions. In a similar way to the backend tech one, I'll post a comment for a few different frameworks, vote on those and feel free to add to the conversation in comments below!

**Comment by mckernanin** [comment]
React

**Comment by mckernanin** [comment]
Vue

**Comment by mckernanin** [comment]
Angular

**Comment by mckernanin** [comment]
I'll update this tomorrow, for now just pasting what I said on discord:

> i'll post more thoroughly once there's a place on github, but i think that react is the way to go for webapps. code portability to a mobile app in the future (react native) is really nice, there are also tons of great tools out there for doing partial server rendering for apps with react. also something i'm working in every day and am very comfortable architecting something big in

**Comment by pscn** [comment]
Let's go with React.  If there is strong arguments against it, we can re-open this issue.
