### ISSUE TITLE
RFC#3: Persistence layer

### ISSUE THREAD

**Issue by ayan4m1** [Korlimann/MixnJuice#3]
As I see it, there are three models we can use for persistence of data:

- Relational - MySQL, PostgreSQL
- Non-relational - Elasticsearch, MongoDB
- Hybrid - Both relational and non-relational persistence

The relational database is best suited for user information and _could_ store everything. However, a non-relational database like elasticsearch or mongodb could be better for recipes, tagging, and search performance. That would lead me to conclude that a hybrid model might be worth the otherwise significant cost (in terms of code complexity and application architecture) of leveraging both simultaneously.

**Comment by chommsi** [comment]
Although I have worked almost only with MySQL and a little bit with MongoDB as far as I remember, I'd say Hybrid sounds best. I would have to dig a bit into it in order to help on this end - if help is needed

**Comment by daviddyess** [comment]
Please keep in mind this may, at least temporarily, be dependent on the data we (may) receive from ATF. Data can be formatted or transposed programmatically, so I'm not saying it's necessarily a restriction, just a possible temporary issue.

**Comment by daviddyess** [comment]
As someone who generally stands behind relational data, I will admit a document system is potentially better suited for at least some aspects of what we are wanting to do. 

PostgreSQL can handle both relational data and documents. MySQL can as well, as of v.5.7. Even though I've used MySQL more, I feel PostgreSQL may be better suited for our needs.

Whatever we decide, speaking as someone who doesn't have unlimited resources (read money), I'm not sure we should lock ourselves into a particular service or provider. Those tend to be designed to make you dependent on them.

I vote for PostgreSQL to be used in a hybrid schema and, just to be a devil's advocate, also nominate ArangoDB for consideration.

**Comment by pscn** [comment]
See #7 for the votes.  Will probably be a hybrid down the road, but let's go with PostgreSQL for now.
