### ISSUE TITLE
Recipe "Actuals" when mixing

### ISSUE THREAD

**Issue by mckernanin** [Korlimann/MixnJuice#30]
Just mixed up 240ml, it'd be nice to be able to enter what percentages you actually used when mixing. Some times you're feeling a certain flavor could be more pronounced, other times you're heavy handed with a flavor and don't want to toss a batch.

**Comment by pscn** [comment]
This is also on my wish list (see #10).  My motivation is more OCD, because sometimes I add a little too much and want to keep my inventory (more or less) accurate.

**Comment by mckernanin** [comment]
Damn, I totally missed that one! I'll go ahead and close this, and add a comment over on your flavor stash issue
