### ISSUE TITLE
RFC#5: Where to discuss features, user stories …

### ISSUE THREAD

**Issue by pscn** [Korlimann/MixnJuice#5]
Right now we have [this](https://github.com/Korlimann/MixnJuice/wiki/Ideas,-Suggestions-and-Features) as a collection of requests / requirements found in the [reddit post](https://www.reddit.com/r/DIY_eJuice/comments/bkcdim/we_need_a_better_ejuice_calculator_help_us_build/).  I'd like to have a place to summarize and discuss these requirements.  I think the Wiki is a great place to write down on what we decided.  But where do we want to discuss it?  I fear that issues get out of hand if the discussion gets too long.  But maybe that's without a basis and issues are the way to go.  What do you all think?

**Comment by chommsi** [comment]
Good point. I think though, we could simply make a label for feature requests so you can filter them out, or filter by other stuff. I don't think too many issues will be a big problem. Besides, you also would have to think about another idea where to discuss stuff like this. Personally I can't think of anything else right now.

**Comment by daviddyess** [comment]
I think discord is good for general discussion and will be useful for talking through issues later. It may be helpful to add more channels for specific topics and areas, to kind of filter that discussion. 

I think the issues can work for us, if we can keep them on point and divided between each issue. Further down the line I see them becoming more specific, whereas starting out, right now, they are more abstract.

**Comment by ayan4m1** [comment]
If we can agree on one, I'd be happy to host an open source project management app.

EDIT: My preference is vaguely towards leaving issues for actual issues - bugs and actionable items, not discussion

**Comment by pscn** [comment]
As discussed on discord, we'll try to work with what github has to offer.  So we use a project in the organization for now.
